[package]
name = "vhost-device-media"
version = "0.1.0"
authors = ["Albert Esteve <aesteve@redhat.com>"]
description = "A virtio-media device using the vhost-user protocol."
repository = "https://github.com/rust-vmm/vhost-device"
keywords = ["vhost", "media", "virt", "backend"]
license = "Apache-2.0 OR BSD-3-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["v4l2-proxy"]
v4l2-proxy = ["v4l2r"]
ffmpeg = ["v4l2r", "virtio-media-ffmpeg-decoder"]
simple-capture = ["v4l2r"]

[dependencies]
bitflags = "2.6.0"
clap = { version = "4.5.20",  features = ["derive"] }
env_logger = "0.11.5"
epoll = "4.3.3"
num_enum = "0.7.3"
log = "0.4.22"
libc = "0.2.162"
thiserror = "2.0.3"
anyhow = "1.0.93"
futures-executor = { version = "0.3.31", features = ["thread-pool"] }
#vhost = { version = "0.12", features = ["vhost-user-backend"] }
vhost = { path = "../../vhost/vhost", features = ["vhost-user-backend"] }
#vhost-user-backend = "0.13"
vhost-user-backend = { path = "../../vhost/vhost-user-backend" }
virtio-bindings = "0.2.4"
virtio-queue = "0.14.0"
vm-memory = "0.16.1"
vmm-sys-util = "0.14.0"
ref-cast = "1.0.23"
virtio-media-ffmpeg-decoder = { path = "../../virtio-media/extras/ffmpeg-decoder", package = "virtio-media-ffmpeg-decoder", optional = true }
#virtio-media-ffmpeg-decoder = { git = "https://github.com/chromeos/virtio-media/", package = "virtio-media-ffmpeg-decoder", version = "0.0.7" }
#virtio-media  = { git = "https://github.com/chromeos/virtio-media/", rev = "b880b0f1b1ca62f4ec861552dcdf80b52b4dcbb6" }
virtio-media = { version = "0.0.7" }
v4l2r = { version = "0.0.7", features = ["arch64"], optional = true }
zerocopy = { version = "0.8.25", features = ["derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.25.0"
tempfile = "3.14.0"
virtio-queue = { version = "0.15.0", features = ["test-utils"] }
vm-memory = { version = "0.16.1", features = ["backend-mmap", "backend-atomic"] }
